### ISSUE TITLE
Underline color collides with spellcheck in Chrome

### ISSUE THREAD

**Issue by sbenario** [cyrusinnovation/just-not-sorry#1]
The color that underlines words currently looks just like the underline that Chrome uses to indicate misspelled words. So when I've written words that get flagged, it's not clear to me if they are simply misspelled, or if JustNotSorry is trying to highlight them.

I'd propose/request the use of a different color -- perhaps purple or blue?

**Comment by blundell** [comment]
+1 m but to have the underline color as a setting

**Comment by lsloan** [comment]
+1  :+1: 

The screenshots on the Chrome web store showed the underlines as yellow or orange.  I am disappointed to see they are actually red when the extension is installed.  It looks very similar to spelling checker underlines.  Many people won't notice the difference and will be annoyed when hovering over or context-clicking the underlined words doesn't work as expected.

This breaks the ages old user interface design "principle of least astonishment" (POLA).  See: https://en.wikipedia.org/wiki/Principle_of_least_astonishment

As @blundell suggests, the color of the underline should be available as an option the user can choose.  I'll go further and suggest that the user be allowed to choose the style as well.  Let the user choose to use underline, overline, strikethrough, boxes, background shading, or maybe even a tiny icon.  By icon, I'm thinking of the tiny triangles that are shown in the corners of Google Sheets cells when there are comments.  For example:

![image](https://cloud.githubusercontent.com/assets/20786/12145061/f4c702ec-b459-11e5-89a8-3ebba4b177dc.png)

**Comment by sbenario** [comment]
FWIW, I totally recognize the vastly increased complexity in adding a
user-facing option for selecting the color and/or indicator. As well as the
fact that "most" users are likely to never use or see it and make do with
the default.

It may be worth splitting this issue out into "change the default color"
and a feature request for "allow users to customize the indicator". :-)

-- My 2c :-)

**Comment by lsloan** [comment]
I won't disagree with putting color and style settings as separate issues.  Whatever fits the workflow best and benefits users the most is the best plan.

PS:  Shouldn't "My 2c" be added to the list of warnings?  It sounds self-deprecating.  :wink:

**Comment by tami-cyrus** [comment]
My two cents was suggest by VOGUE :)

We'll see what we can do about changing the default color in the next few
days.

Any ideas on what you would like it to be?
Colors that are not OK bc of usability: Blue (hyperlink), Green (looks like
a positive), Yellow (contrast)

If we went more towards a yellower orange would that be OK?


-
Tami Reiss
CEO
Cyrus Innovation <http://www.cyrusinnovation.com/>
212-647-7186

Agile Reinforcement to accelerate your development

Dedicated to respect and diversity


@tamireiss / @cyrusinnovation

Learn about the difference between the Cyrus way
<http://www.cyrusinnovation.com/differences-between-xp-vs-scrum-agile/> and
other consultancies.

**Comment by blundell** [comment]
the default as yellow / orange would be great. The problem is like stated above, right now it matches the spellcheck which is wrong I might want to fix one but not the other.

FWIW when you get to X number of users you'll start getting complained for contrasts of colour blind colours.

**Comment by verdammelt** [comment]
@tami-cyrus Let me know what you think of the different options for the underlining:

* dotted ![screen shot 2016-01-08 at 09 04 44](https://cloud.githubusercontent.com/assets/365425/12199591/4254f134-b5e7-11e5-9cc0-ada9bf6f7b33.png)
* dashed ![screen shot 2016-01-08 at 09 05 19](https://cloud.githubusercontent.com/assets/365425/12199593/425a16b4-b5e7-11e5-9589-348b0d6d61be.png)
* double ![screen shot 2016-01-08 at 09 06 46](https://cloud.githubusercontent.com/assets/365425/12199592/42595396-b5e7-11e5-94a8-90c4d716732d.png)

**Comment by tamireiss** [comment]
Let's go dashed.

Tami Reiss
@tamireiss

**Comment by lsloan** [comment]
Dashed line looks nice.  I'm surprised that double doesn't look double.  The style probably has a `border-width` that's interfering with the appearance.  Try removing the width or give it a value of `medium` or `initial`.

**Comment by verdammelt** [comment]
@lsloan quite right there was a border width. Here is a pic without the border width

![screen shot 2016-01-08 at 09 26 00](https://cloud.githubusercontent.com/assets/365425/12199955/ec3c38ae-b5e9-11e5-9f94-c60952c3e7fd.png)

@tami-cyrus what about this option?

**Comment by tami-cyrus** [comment]
Dashed please. Closer is fine.

Tami Reiss
CEO
http://www.cyrusinnovation.com/
@tamireiss
212-647-7186
Agile reinforcement to accelerate your development
Best place in NYC for female founders to build great products

**Comment by verdammelt** [comment]
Dashed it is.

I will create a new issue for the creation of an user-option for the styling. This one will be closed with the above pull request.
