### ISSUE TITLE
cursor moves unexpectedly when changing text props

### ISSUE THREAD

**Issue by sbenario** [cyrusinnovation/just-not-sorry#10]
repro steps:

1) write a few words "the quick brown fox"
2) using the keyboard, highlight the previous 3 words (on a mac, option-shift-leftarrow 3 times)
3) using the keyboard, bold the selection. (on a mac, command-B)

Expected result:  3 highlighted words remain highlighted (now bold)
Actual result while plugin enabled:  3 highlighted words are bolded, cursor is moved to the end.

This is kind of a workflow killer for keyboard users :-/

**Comment by verdammelt** [comment]
Easy to reproduce.

**Comment by tami-cyrus** [comment]
https://github.com/cyrusinnovation/just-not-sorry/issues/31
