### ISSUE TITLE
disabled extension continues to run

### ISSUE THREAD

**Issue by lsloan** [cyrusinnovation/just-not-sorry#21]
When just-not-sorry is disabled in Chrome (by going to chrome://extensions/ and unchecking the "Enabled" checkbox), the JNS icon is immediately removed from the address bar.  However, Google Mail windows that were open when JNS was running will continue to run.  If the page is reloaded, JNS will no longer run.  Doing that will not be immediately obvious the the majority of users.

Add a check to the code to not run if the extension is not enabled.

**Comment by lsloan** [comment]
http://stackoverflow.com/questions/6293498/check-whether-user-has-a-chrome-extension-installed

**Comment by tami-cyrus** [comment]
Sorry about that. Is this still an issue. You may need to reload chrome. Please reopen if still an issue.
