### ISSUE TITLE
Cursor incorrectly skips to the previous line when deleting all characters in a line

### ISSUE THREAD

**Issue by lyanco** [cyrusinnovation/just-not-sorry#22]
Setup: Open a reply in gmail, type some stuff, press enter to go to a new line and type some more stuff

Action: Press backspace to delete all the characters in the new line

Expected: Cursor stays on that new line

Actual: Cursor jumps to the end of the previous line

Confirmed that is the Just Not Sorry app causing this by disabling it and noticing the behavior stopped, then re-enabling and seeing the behavior happen again.

Using Chrome 47.0.2526.106 (64-bit) on Mac OSX 10.9.5

**Comment by sbrudz** [comment]
This bug is fixed in the v0.2.6 update, which is on the Chrome Web Store now and will be published to everyone via Chrome's auto-update soon.  Thanks for reporting it and thanks for your patience.
