### ISSUE TITLE
Spell check triggers on character press

### ISSUE THREAD

**Issue by lyanco** [cyrusinnovation/just-not-sorry#27]
Seems like with the newest update, the spellchecker triggers on keypress, so words get underlined as incorrect when you're in the middle of typing them. 

Interestingly this only happens on my work gmail, not my personal. Will keep digging to see if I can get better reproduction information than that.

**Comment by randallreedjr** [comment]
@lyanco We noticed something similar with other Gmail Chrome extensions installed at the same time. What other extensions are you using?

**Comment by lyanco** [comment]
The only other gmail plugin I have running is Giphy, but it's running on both my work and personal chrome instances so I don't think that's it.

**Comment by tami-cyrus** [comment]
We're hoping that https://github.com/cyrusinnovation/just-not-sorry/issues/31 fixes this
