### ISSUE TITLE
Not working (edit: conflict with Boomerang for Gmail extension)

### ISSUE THREAD

**Issue by mrjustin** [cyrusinnovation/just-not-sorry#3]
~~Sorry~~ I was ~~just~~ testing out the extension and sadly it doesn't seem to be working.

Restarted Chrome
Disabled other Gmail-related extensions
Tried in Incognito window

Chrome Version 47.0.2526.106 (64-bit)
OSX 10.11.2

Anybody else having trouble or is this me?

Screenshot:
![20151228-103009](https://cloud.githubusercontent.com/assets/233177/12023408/1693f9b0-ad4e-11e5-993d-f8c259a20228.jpg)

**Comment by sbrudz** [comment]
Hi @mrjustin,

I'm sorry to hear that you're having trouble running the extension.  Please try the following steps to provide more information for troubleshooting:
  1. Open the Chrome developer console (View menu -> Developer -> JavaScript Console) 
  2. Navigate to Gmail (or click the refresh button if already on that page)
  3. Click the Compose button
  4. Type something into the compose window
  5. Capture whatever messages are in the Chrome developer console and attach them to this ticket

Thank you,

Steve

**Comment by mrjustin** [comment]
After more testing, it looks like the conflict is with the [Boomerang for Gmail](https://chrome.google.com/webstore/detail/boomerang-for-gmail/mdanidgdpmkimeiiojknlnekblgmpdll) extension.

When both are the only enabled extensions, I get the following console error when composing a new message (the last error appears every time a key is pressed):
![20151228-121126](https://cloud.githubusercontent.com/assets/233177/12024749/5589a152-ad5c-11e5-8d66-02313c770b6c.jpg)

I also noticed this error when clicking on a message (which looks to be caused by Boomerang):
![20151228-121408](https://cloud.githubusercontent.com/assets/233177/12024769/867ac426-ad5c-11e5-94b5-5067f0378a37.jpg)

(Not sure if the issue is caused by you or them, though frankly I'm OK disabling Boomerang as I don't use it much these days)

**Comment by tami-cyrus** [comment]
Cool! Thanks for the diagnosis. Steve is on vacation for the rest of the
week. We'll see what we can do in the new year.

-
Tami Reiss
CEO
Cyrus Innovation <http://www.cyrusinnovation.com/>
212-647-7186

Agile Reinforcement to accelerate your development

Dedicated to respect and diversity


@tamireiss / @cyrusinnovation

Learn about the difference between the Cyrus way
<http://www.cyrusinnovation.com/differences-between-xp-vs-scrum-agile/> and
other consultancies.

**Comment by sbrudz** [comment]
It looks like there's some sort of bad jQuery-related interaction going on between the plugins.  I'll take a closer look next week.  Thanks for reporting this and helping to track it down!

**Comment by tami-cyrus** [comment]
We're hoping https://github.com/cyrusinnovation/just-not-sorry/issues/31 will fix this.

**Comment by sbrudz** [comment]
Yes, this is fixed in the 1.0 release of JustNotSorry (by #31).
