### ISSUE TITLE
Mac OSX Mail Plugin?

### ISSUE THREAD

**Issue by air720boarder** [cyrusinnovation/just-not-sorry#33]
Can you publish a Mac OS X Mail Plugin?

**Comment by sbrudz** [comment]
We won't be able to publish JustNotSorry as an OS X Mail plug-in for these reasons:

  1. Apple does not provide an official plugin API for the OS X Mail application.  There is an unofficial API that people can use but there's a risk of the plugin breaking anytime Apple releases an update.  Apple also won't let people release these plug-ins on the App Store, so it's harder to distribute them.
  1. OS X Mail plug-ins need to be written in Objective C whereas JustNotSorry is written in JavaScript.  Adapting it for an OS X Mail plug-in would require a complete rewrite.

It's definitely possible but it's not something we have time to do.  If you or someone else in the community would like to work on a version of JustNotSorry for OS X Mail, please feel free to do so.  It would be really cool.
