### ISSUE TITLE
Add warnings based on article "Want to Be a Better Writer? Cut These 7 Words"

### ISSUE THREAD

**Issue by mollym0** [cyrusinnovation/just-not-sorry#35]
http://thewritepractice.com/better-writer-now/ explains why the following words / phrase could negatively impact someone's message.

“One of”
"Some"
“Thing”
“Very”
"So, mostly, most times, in order to, often, oftentimes"

The article lists others, but warning underlines for the above would help users of the just-not-sorry extension write with greater clarity and specificity. 

Thanks for this helpful extension and your consideration of this suggestion.

**Comment by sbrudz** [comment]
Dear @mollym0,

Thank you so much for your suggestion.  I discussed this with @tami-cyrus and we decided that while writing well is important, adding these words is too much outside of the core idea for Just Not Sorry and since they're commonly used might end up highlighting too many items.

Sincerely,

Steve

**Comment by mollym0** [comment]
Understood! Thank you for the response. Just Not Sorry is so helpful. Maybe
it's the beginnings of your next popular add-on (wink wink).
Meanwhile I might use aText to make those words all-caps or bold when I
type them to remind me to write better.
Appreciate your consideration. Keep up the good work!
Molly


*MOLLY MORRIS FUTRELL*
Pardot Client Advocate Team Lead, AMER East & EMEA | Salesforce
molly.morris@salesforce.com | +1 404.804.1836 | Atlanta, GA

Knowledge Base <http://help.pardot.com/> | eLearning
<http://www.pardot.com/training> | Success Community
<http://www2.pardot.com/success> | Office Hours
<http://www2.pardot.com/advocates>
[image: Screen Shot 2016-02-29 at 11.47.02 AM.png]
--
--
