### ISSUE TITLE
Not encoding correctly?

### ISSUE THREAD

**Issue by blundell** [cyrusinnovation/just-not-sorry#5]
Just installed and testing on my gmail:

![screen shot 2015-12-30 at 10 10 54 am](https://cloud.githubusercontent.com/assets/655860/12049349/dc77df08-aedd-11e5-8d22-f30e399d0880.png)

seems to be missing some decoding perhaps?

**Comment by sbrudz** [comment]
Good catch.  Thanks for reporting it!  I'll release an update to the Chrome Web Store shortly.

**Comment by blundell** [comment]
:+1:
