### ISSUE TITLE
Issue with line breaks

### ISSUE THREAD

**Issue by tamarw** [cyrusinnovation/just-not-sorry#8]
Hi - when the plugin is enabled, my line breaks aren't being respected especially when trying to hit backspace a few times to join two lines together.

Not sure how best to illustrate this outside a screencast which I can do if need be.

**Comment by sbrudz** [comment]
No need for a screencast.  I'm seeing it, too.  The root cause is the same as issue #6.  I'm working on a fix.

**Comment by verdammelt** [comment]
Duplicate of #6.
